LICENSE, README.md
Added license and comments on README.
=> Package help

iematch.do
This file was developed in the matchIE repo in kbjarkefur's private
account. This will be included in this branch from now on
=> Add iematch test file to branch

iebaltab.ado, iebaltab.sthlp, ieboilsave.ado, ieboilsave.sthlp, ieboilstart.ado, ieboilstart.sthlp, iecompdup.ado, iecompdup.sthlp, ieduplicates.ado, ieduplicates.sthlp
Update version number after having an incorrect command name for
ieboilstart
=> Update version number

iebaltab.do, iebaltab.sthlp, test iebaltab.do
Included option to export balance table for latex
=> Develop iebaltab latex

iebaltab.ado
this commit fixes issue number 16. Robust was not allowed in mean, but
mean is only used to something where robust does not matter. the
temporary text file for both latex and regular are referenced in the
recommended way so that they work in Windows 10 as well.
=> iebaltab : textfile, robust

iebaltab.sthlp
Usually this is only done when we release a new version, but this was done for training purposes
=> Merge some minor changes from the develop branch

.gitignore, README.md
folders names test and all their content is now ignored. copy to all branches
=> merge settings ignoring the test folder

.gitignore, ieimp2.do, ieimpgraph2.do
Merging to ieimpgraph branch on main repo before presenting half baked commands to rest of DIME
=> Lightening seminar half baked commit

functions.do
=> Typo Correction

iedropone.sthlp
Minor changes to the language in a couple of places.
=> Minor changes

iebaltab.ado, iebaltab.sthlp
Fixing the following issues:
#58 
#55 
#54 
#53
=> Creating pull request from Luzia's fork

src/ado_files/iefolder.ado
Creates an import task master do file in the encrypted folder
=> fix issue #71 - create import task master

src/ado_files/iegraph.ado, src/help_files/iegraph.sthlp
Fix to issue #82. Squashed merge. Restore branch for individual updates.
=> Issue 82 0- yzero() for negative values

src/ado_files/iefolder.ado, src/help_files/iefolder.sthlp
In order to make each round master dofile possible to run independently of the project master do file this issue #84 together with issue #80 fixes that.
Following this merge, a *global_setup.do* file is created and called from each round master dofile.
=> Issue #84 - Create the constant globals in each round master

src/ado_files/iefolder.ado
fixes issue #89 
Removes subfolder and rename folders in EncryptedData
=> fix issue #89 - remove IDMasterKey

src/ado_files/iegitaddmd.ado, src/help_files/iebaltab.sthlp, src/help_files/iecompdup.sthlp, src/help_files/iedropone.sthlp, src/help_files/ieduplicates.sthlp, src/help_files/iegitaddmd.sthlp
Sorry, I got the name of the commit wrong. My bad.
=> iegitaddmd : Fixes Issue #118

src/help_files/iefolder.sthlp
Corrected spelling from untiofobs to unitof obs
=> Spelling correction

src/ado_files/iefolder.ado
Added deidentified folder to datasets folder for new rounds
=> Fix issue #145

src/ado_files/iefolder.ado
Correcting spelling from WRITEN BY to WRITTEN BY.
=> Fix typo in title of the master dofile

src/ado_files/ieduplicates.ado
Temporary fix with better error message to issue #152 to be included in the version 5.6.
A final fix to this issue will be included in the following version of **ietoolkit**.
=> iedup : tempfix to #152

README.md, src/help_files/iebaltab.sthlp, src/help_files/ieboilsave.sthlp, src/help_files/ieboilstart.sthlp, src/help_files/iecompdup.sthlp, src/help_files/iedropone.sthlp, src/help_files/ieduplicates.sthlp, src/help_files/iefolder.sthlp, src/help_files/iegitaddmd.sthlp, src/help_files/iegraph.sthlp, src/help_files/iematch.sthlp, src/help_files/ietoolkit.sthlp
All helpfiles are updated with the DIME Analytics as author and the person who implemented it the "main author".
And update the email address to point to dime analytics
=> all helpfiles: fix issue #153

src/ado_files/iebaltab.ado, src/help_files/iebaltab.sthlp
=> iebaltab: fix weight bug

src/ado_files/ieddtab.ado, src/help_files/ieddtab.sthlp
=> Add [weight] option to ieddtab

src/ado_files/ieddtab.ado, src/help_files/ieddtab.sthlp
Fixing #165 was quite straightforward given the setup we are using in `ieddtab`. I am looking forward to when we have re-written `iebaltab`.
@luizaandrade , do you want to test with your LaTeX options that it works as intended?
=> Add option to suppress starts in tables - issue #165

src/ado_files/ieddtab.ado, src/help_files/ieddtab.sthlp
I think this works. I did create the branch from develop before the merge of the last pull requests, so there will probably be conflicts 😀
=> Develop issue 161

src/ado_files/iebaltab.ado, src/ado_files/ieboilsave.ado, src/ado_files/ieboilstart.ado, src/ado_files/iecompdup.ado, src/ado_files/ieddtab.ado, src/ado_files/iedropone.ado, src/ado_files/ieduplicates.ado, src/ado_files/iefolder.ado, src/ado_files/iegitaddmd.ado, src/ado_files/iegraph.ado, src/ado_files/iematch.ado, src/ado_files/ietoolkit.ado, src/help_files/iebaltab.sthlp, src/help_files/ieboilsave.sthlp, src/help_files/ieboilstart.sthlp, src/help_files/iecompdup.sthlp, src/help_files/ieddtab.sthlp, src/help_files/iedropone.sthlp, src/help_files/ieduplicates.sthlp, src/help_files/iefolder.sthlp, src/help_files/iegitaddmd.sthlp, src/help_files/iegraph.sthlp, src/help_files/iematch.sthlp, src/help_files/ietoolkit.sthlp
This is related to the checklist in #174
=> Pull request for version 6.1.

src/ado_files/ieduplicates.ado
=> Merge the solution to issue #188

run/iekdensity.do, src/ado_files/iekdensity.ado, src/help_files/iekdensity.sthlp
Suggested changes to commands' syntax
=> Iekdensity syntax

src/help_files/iebaltab.sthlp
Add text about categorical variables in helpfile and suggest command `table1` for now.
=> [iebaltab] categorical variables - help file #231

.gitignore, run/ie_recurse_rmdir.do, run/iegitaddmd.do, src/ado_files/iegitaddmd.ado, src/help_files/iegitaddmd.sthlp
Suggested solution to #229 
@bbdaniels can you test and merge?
=> Iegitaddmd - issue 229 - skip .git folder and option for skipping more folders

run/ieddtab.do, src/ado_files/ieddtab.ado
Solves issue #237 and sets up a test file that would have prevented this bug in the first place.
@luizaandrade, I think the implementation of the test file ended up neat. We should do something similar in `iebaltab`.
=> Ieddtab issue 237

src/ado_files/ieboilsave.ado
=> [iesave] save data

src/ado_files/iegraph.ado, src/help_files/iegraph.sthlp
=> Iegraph label issue271

src/ado_files/ieboilstart.ado
=> [ieboilstart] - set type and set rng

src/ado_files/iematch.ado
Fix to issue if IDs are so long the need to be in double type - issue #252 
Also labeled tempvars to simplify future troubleshooting
=> [iematch] - issues with long IDs

src/ado_files/iebaltab.ado
Fix to small but major bug in `iebaltab`. See #311
=> PR for version 7.1

run/ieboilstart.do, src/ado_files/ieboilstart.ado, src/help_files/ieboilstart.sthlp
Version to be released before blogpost on `adopath()`
=> v7.2 - nostrict option `ieboilstart, adopath()`

src/help_files/iesave.sthlp
Fix issue #329 
Updates outdates name to new name in helpfile
=> iesave? : update outdated name used in helpfile

run/iedorep/iedorep-target-1.do, run/iedorep/iedorep/iedorep-target-1.dorep.smcl, run/iedorep/iedorep/run1/m.do, run/iedorep/iedorep/run1/m_1.do, run/iedorep/iedorep/run1/m_1_1.do, run/iedorep/iedorep/run2/m.do, run/iedorep/iedorep/run2/m_1.do, run/iedorep/iedorep/run2/m_1_1.do, run/iedorep2-run/loop-file/output/iedorep/main.dorep.smcl, run/iedorep2-run/multi-file/output/iedorep/main.dorep.smcl, run/iedorep2-run/multi-file/output_verbose/iedorep/main.dorep.smcl, run/iedorep2-run/single-file/output/iedorep/main.dorep.smcl, src/ado_files/iedorep.ado, src/ado_files/iedorep_dataline.ado
@kbjarkefur to fully check quote handling before merging
=> Attempt quote fix

src/ado/iesave.ado, src/mdhlp/iesave.md, src/sthlp/iesave.sthlp
=> Iesave - updated help files

src/ado/ieddtab.ado, src/mdhlp/ieddtab.md, src/sthlp/ieddtab.sthlp
=> Ieddtab - updated help files

src/ado/ieboilstart.ado, src/mdhlp/ieboilstart.md, src/sthlp/ieboilstart.sthlp
Tables in "Other Settings" not displaying properly
=> Ieboilstart help files
